// Generated by scripts/generate-secret-rules.mjs from shared/canonical-secret-rules.json. DO NOT EDIT.
import Foundation

enum CanonicalSecretRuleCorpus {
    static let ruleIDs = ["github-prefixed-token", "github-fine-grained-token", "sk-provider-key", "bearer-credential", "credential-url", "aws-access-key", "slack-token", "query-credential", "customer-id", "customer-ssn", "customer-phone", "named-credential", "neondiff-underscore-license", "neondiff-live-license", "neondiff-hyphen-license", "hyphenated-named-credential", "email-address", "complete-private-key", "truncated-private-key", "sensitive-cookie-header"]
    static let sensitive: [(id: String, text: String)] = [
        ("github-prefixed-token", "ghp_abcdefgh"),
        ("github-fine-grained-token", "github_pat_abcdefgh"),
        ("sk-provider-key", "sk-abcdefgh"),
        ("bearer-credential", "Bearer abcdefghijklmnopqrst"),
        ("credential-url", "https://user:p4ss@example.com/path"),
        ("aws-access-key", "AKIA1234567890ABCDEF"),
        ("slack-token", "xoxb-abcdefghij"),
        ("query-credential", "?access_token=abcdefghijklmnop"),
        ("customer-id", "customer_id=cus_abcdefgh"),
        ("customer-ssn", "client_ssn=123-45-6789"),
        ("customer-phone", "customer_phone=+1 (415) 555-0123"),
        ("named-credential", "password=abcdefghijklmnop"),
        ("neondiff-underscore-license", "NEONDIFF_abcdefghijkl"),
        ("neondiff-live-license", "nd_live_abcdefgh"),
        ("neondiff-hyphen-license", "NDL-XQKM-RPYB-SUTE"),
        ("hyphenated-named-credential", "super-secret-token"),
        ("email-address", "person@example.com"),
        ("complete-private-key", ["-----BEGIN ", "PRIVATE KEY-----\\nabc\\n-----END ", "PRIVATE KEY-----"].joined()),
        ("truncated-private-key", ["-----BEGIN ", "PRIVATE KEY-----\\nabc"].joined()),
        ("sensitive-cookie-header", "Cookie: theme=light; session=x"),
    ]
    static let benign: [(id: String, text: String)] = [
        ("ordinary-provider-status", "Provider metadata endpoint is healthy."),
        ("short-sk-fragment", "sk-short"),
        ("ordinary-neondiff-path", "/tmp/neondiff-launchd-plist-Ov4D5v/com.example.neondiff.plist"),
        ("lowercase-license-label", "lic-diagnostic-reference-without-key-material"),
        ("safe-environment-names", "Set NEONDIFF_GITHUB_APP_ID, NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH, NEONDIFF_LICENSE_KEY, and NEONDIFF_PROVIDER_API_KEY."),
        ("non-sensitive-cookie", "Cookie: theme=light; locale=en-US"),
        ("customer-label", "customer_id = acme-corporation-12345"),
    ]
}
