import { mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { validateDesktopReleaseDeclaration, validateDesktopReleaseIndex } from "../scripts/validate-desktop-release-declaration.mjs";

const declaration = (version = "1.1.0-beta.1") => ({ schemaVersion: "desktop-release-declaration.v1", product: "NeonDiff Desktop", version, tag: `v${version}`, build: "1101", contract: version === "1.1.0" ? "paid-mac-ga-byo-v1" : "paid-mac-beta-byo-v1", distribution: { bundleId: "com.electricsheephq.NeonDiffDesktop", appPath: "NeonDiff.app", artifactName: `NeonDiffDesktop-${version}.zip`, releaseClass: "desktop-only", origins: { github: "https://github.com/electricsheephq/evaos-code-review-bot-neondiff", site: "https://www.neondiff.com", feed: "https://updates.neondiff.com" } } });
function fixture(status = "empty", files: Record<string, unknown> = {}) { const root = mkdtempSync(join(tmpdir(), "neondiff-release-")), dir = join(root, "desktop"); mkdirSync(dir); for (const [name, value] of Object.entries(files)) writeFileSync(join(dir, name), JSON.stringify(value)); const index = join(root, "index.json"); writeFileSync(index, JSON.stringify({ schemaVersion: "desktop-release-index.v1", status, declarationDirectory: "desktop", declarationPaths: Object.keys(files), currentPath: status === "current" ? Object.keys(files)[0] : null })); return { root, index }; }
describe("Desktop release declaration/index", () => {
  it("accepts canonical beta, RC, stable identities and contracts", () => { for (const version of ["1.1.0-beta.1", "1.1.0-rc.12", "1.1.0"]) expect(validateDesktopReleaseDeclaration(declaration(version)).valid).toBe(true); });
  it("rejects leading-zero/zero versions, drift, proof fields, and machine paths", () => { for (const version of ["1.1.0-beta.0", "1.1.0-beta.01", "1.1.0-rc.01", "1.1.1"]) expect(validateDesktopReleaseDeclaration(declaration(version)).valid).toBe(false); const bad = declaration(); bad.tag = "v1.1.0-rc.1"; (bad as any).proof = ["pending"]; expect(validateDesktopReleaseDeclaration(bad).valid).toBe(false); const path = declaration(); path.distribution.appPath = "/Applications/NeonDiff.app"; expect(validateDesktopReleaseDeclaration(path).valid).toBe(false); });
  it("fails closed when Ajv is unavailable", () => { expect(validateDesktopReleaseDeclaration(declaration(), { ajv: null })).toEqual({ valid: false, errors: ["schema validator unavailable"] }); const empty = fixture(); expect(validateDesktopReleaseIndex(empty.index, { ajv: null })).toEqual({ valid: false, errors: ["schema validator unavailable"] }); rmSync(empty.root, { recursive: true, force: true }); });
  it("accepts empty/current indexes and rejects unindexed, traversal, nested, or symlink JSON", () => { const empty = fixture(); expect(validateDesktopReleaseIndex(empty.index).valid).toBe(true); rmSync(empty.root, { recursive: true, force: true }); const current = fixture("current", { "v1.1.0-beta.1.json": declaration() }); expect(validateDesktopReleaseIndex(current.index).valid).toBe(true); writeFileSync(join(current.root, "desktop", "v1.1.0-rc.1.json"), JSON.stringify(declaration("1.1.0-rc.1"))); expect(validateDesktopReleaseIndex(current.index).valid).toBe(false); rmSync(current.root, { recursive: true, force: true }); const unsafe = fixture(); const index = JSON.parse(readFileSync(unsafe.index, "utf8")); index.declarationDirectory = "../"; writeFileSync(unsafe.index, JSON.stringify(index)); expect(validateDesktopReleaseIndex(unsafe.index).valid).toBe(false); rmSync(unsafe.root, { recursive: true, force: true }); const linked = fixture("current", { "v1.1.0-beta.1.json": declaration() }); symlinkSync(join(linked.root, "desktop", "v1.1.0-beta.1.json"), join(linked.root, "desktop", "v1.1.0-rc.1.json")); expect(validateDesktopReleaseIndex(linked.index).valid).toBe(false); rmSync(linked.root, { recursive: true, force: true }); });
});
