// Generated by scripts/generate-secret-rules.mjs from shared/canonical-secret-rules.json. DO NOT EDIT.
export const canonicalSecretRuleCorpus = {
  ruleIds: [
  "github-prefixed-token",
  "github-fine-grained-token",
  "sk-provider-key",
  "bearer-credential",
  "credential-url",
  "aws-access-key",
  "slack-token",
  "query-credential",
  "customer-id",
  "customer-ssn",
  "customer-phone",
  "named-credential",
  "neondiff-underscore-license",
  "neondiff-live-license",
  "neondiff-hyphen-license",
  "hyphenated-named-credential",
  "email-address",
  "complete-private-key",
  "truncated-private-key",
  "sensitive-cookie-header"
],
  sensitive: [
    { id: "github-prefixed-token", text: "ghp_abcdefgh" },
    { id: "github-fine-grained-token", text: "github_pat_abcdefgh" },
    { id: "sk-provider-key", text: "sk-abcdefgh" },
    { id: "bearer-credential", text: "Bearer abcdefghijklmnopqrst" },
    { id: "credential-url", text: "https://user:p4ss@example.com/path" },
    { id: "aws-access-key", text: "AKIA1234567890ABCDEF" },
    { id: "slack-token", text: "xoxb-abcdefghij" },
    { id: "query-credential", text: "?access_token=abcdefghijklmnop" },
    { id: "customer-id", text: "customer_id=cus_abcdefgh" },
    { id: "customer-ssn", text: "client_ssn=123-45-6789" },
    { id: "customer-phone", text: "customer_phone=+1 (415) 555-0123" },
    { id: "named-credential", text: "password=abcdefghijklmnop" },
    { id: "neondiff-underscore-license", text: "NEONDIFF_abcdefghijkl" },
    { id: "neondiff-live-license", text: "nd_live_abcdefgh" },
    { id: "neondiff-hyphen-license", text: "NDL-XQKM-RPYB-SUTE" },
    { id: "hyphenated-named-credential", text: "super-secret-token" },
    { id: "email-address", text: "person@example.com" },
    { id: "complete-private-key", text: ["-----BEGIN ", "PRIVATE KEY-----\\nabc\\n-----END ", "PRIVATE KEY-----"].join("") },
    { id: "truncated-private-key", text: ["-----BEGIN ", "PRIVATE KEY-----\\nabc"].join("") },
    { id: "sensitive-cookie-header", text: "Cookie: theme=light; session=x" },
  ],
  benign: [
  {
    "id": "ordinary-provider-status",
    "text": "Provider metadata endpoint is healthy."
  },
  {
    "id": "short-sk-fragment",
    "text": "sk-short"
  },
  {
    "id": "ordinary-neondiff-path",
    "text": "/tmp/neondiff-launchd-plist-Ov4D5v/com.example.neondiff.plist"
  },
  {
    "id": "lowercase-license-label",
    "text": "lic-diagnostic-reference-without-key-material"
  },
  {
    "id": "safe-environment-names",
    "text": "Set NEONDIFF_GITHUB_APP_ID, NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH, NEONDIFF_LICENSE_KEY, and NEONDIFF_PROVIDER_API_KEY."
  },
  {
    "id": "non-sensitive-cookie",
    "text": "Cookie: theme=light; locale=en-US"
  },
  {
    "id": "customer-label",
    "text": "customer_id = acme-corporation-12345"
  }
]
} as const;
