import { beforeEach, describe, expect, it, vi } from "vitest";
import { createTestLicenseAdmission } from "./helpers/license-admission.js";
const { prepareBranchWorktree, runIssueAnalysis } = vi.hoisted(() => ({ prepareBranchWorktree: vi.fn(), runIssueAnalysis: vi.fn(async () => ({ analysis: { classification: "needs-repro", priority: "P3", priorityState: "provisional", confidence: "needs-repro", repositoryImpact: "fixture", currentMainApplicability: "fixture", verifiedFacts: [], reproductionOrInvariantGap: "fixture", relatedWork: [], migrationDisposition: "needs-repro", nextGate: "fixture", limitations: [], labelProposals: [] } })) }));
vi.mock("../src/git.js", async (original) => ({ ...await original<typeof import("../src/git.js")>(), prepareBranchWorktree }));
vi.mock("../src/issue-analysis.js", async (original) => ({ ...await original<typeof import("../src/issue-analysis.js")>(), runIssueAnalysis }));
import { runIssueEnrichmentCycle } from "../src/issue-enrichment.js";
const config = (allowlist: string[]) => ({ workRoot: "/tmp/work", evidenceDir: "/tmp/evidence", codexRuntime: { enabled: true, cliPath: "/usr/bin/false", model: "fixture", reasoningEffort: "low" as const, timeoutMs: 1, maxOutputBytes: 1 }, issueEnrichment: {
  enabled: true, postIssueComment: true, allowlist, allowedLabels: [], allowedReviewers: [], maxIssuesPerCycle: 1, maxCommentsPerCycle: 1, globalMaxIssuesPerCycle: 1, globalMaxCommentsPerCycle: 1, maxActiveRuns: 1, leaseTtlMs: 60_000, cooldownMs: 60_000, burstWindowMs: 60_000, maxIssuesPerBurst: 1, lookbackMs: 60_000, processExistingOpenIssuesOnActivation: true,
  repos: Object.fromEntries(allowlist.map((repo) => [repo, { maxIssuesPerCycle: 1, maxCommentsPerCycle: 1, cooldownMs: 60_000, burstWindowMs: 60_000, maxIssuesPerBurst: 1, lookbackMs: 60_000 }]))
} });
const state = () => ({ getIssueEnrichmentRecord: () => undefined, recordIssueEnrichment: (value: unknown) => value as never, getIssueEnrichmentRepoWatermark: () => undefined, recordIssueEnrichmentRepoWatermark: (value: unknown) => value as never, tryAcquireIssueEnrichmentRunLease: () => ({ leaseId: "fixture", expiresAt: "2026-08-26T10:01:00.000Z", ownerPid: 1 }), releaseIssueEnrichmentRunLease: () => undefined });
const persistentState = (initial: any[] = []) => { const records = new Map<string, any>(initial.map((record) => [`${record.repo}#${record.issueNumber}`, record])); return { ...state(), getIssueEnrichmentRecord: (repo: string, issueNumber: number) => records.get(`${repo}#${issueNumber}`), recordIssueEnrichment: (value: any) => { const { now: _now, ...stored } = value; records.set(`${stored.repo}#${stored.issueNumber}`, stored); return stored; } }; };
const issue = (number: number) => ({ number, title: `Issue ${number}`, state: "open", updated_at: "2026-08-26T09:00:00.000Z", body: "Acceptance criteria and owner present." });
const admission = await createTestLicenseAdmission({ operation: "issue_enrichment" });
describe("issue-enrichment lazy source settlement", () => {
  beforeEach(() => vi.clearAllMocks());
  it("does not prepare source for an empty repository scan", async () => { prepareBranchWorktree.mockResolvedValue({ path: "/tmp/unused", headSha: "a".repeat(40) }); const result = await runIssueEnrichmentCycle({ config: config(["owner/empty"]), state: state(), github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [], canPostAsApp: () => true, upsertIssueComment: async () => { throw new Error("must not post"); } }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(result.summary).toMatchObject({ issuesSeen: 0, posted: 0, failed: 0 }); expect(prepareBranchWorktree).not.toHaveBeenCalled(); });
  it("keeps repository identity stable across case-variant allowlist order", async () => { const sharedState = persistentState(), posted: number[] = []; prepareBranchWorktree.mockResolvedValue({ path: "/tmp/repo", headSha: "a".repeat(40) }); const github = { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [issue(1)], getIssueOrPull: async () => issue(1), canPostAsApp: () => true, upsertIssueComment: async ({ issueNumber }: { issueNumber: number }) => { posted.push(issueNumber); return { action: "created" as const, id: issueNumber }; } }; for (const allowlist of [["Owner/Repo", "owner/repo"], ["owner/repo", "Owner/Repo"]]) await runIssueEnrichmentCycle({ config: config(allowlist), state: sharedState, github, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(posted).toEqual([1]); const scanned: string[] = []; await runIssueEnrichmentCycle({ config: config(["z/repo", "a/repo"]), state: state(), github: { ...github, listIssuesForEnrichment: async (repo: string) => { scanned.push(repo); return []; } }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(scanned).toEqual(["z/repo", "a/repo"]); const disabled = config(["owner/repo", "Owner/Repo"]); delete disabled.issueEnrichment.repos["Owner/Repo"]; (disabled.issueEnrichment.repos["owner/repo"] as any).enabled = false; const disabledList = vi.fn(async () => [issue(1)]), disabledResult = await runIssueEnrichmentCycle({ config: disabled, state: state(), github: { ...github, listIssuesForEnrichment: disabledList }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(disabledResult.status.ok).toBe(true); expect(disabledList).not.toHaveBeenCalled(); });
  it("releases preparation failures and backfills a healthy repository", async () => { const repos = ["owner/fail-a", "owner/fail-b", "owner/healthy"], posted: number[] = []; prepareBranchWorktree.mockImplementation(async ({ repo }: { repo: string }) => { if (repo.includes("fail")) throw new Error("fixture prepare failure"); return { path: "/tmp/healthy", headSha: "a".repeat(40) }; }); const result = await runIssueEnrichmentCycle({ config: config(repos), state: state(), github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async (repo) => [issue(repos.indexOf(repo) + 1)], getIssueOrPull: async (_repo, number) => issue(number), canPostAsApp: () => true, upsertIssueComment: async ({ issueNumber }) => { posted.push(issueNumber); return { action: "created" as const, id: issueNumber }; } }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(result.summary).toMatchObject({ posted: 1, failed: 2, deferredRecorded: 0 }); expect(posted).toEqual([3]); expect(prepareBranchWorktree).toHaveBeenCalledTimes(3); });
  it("releases one evidence failure and reuses the prepared repo for backfill", async () => { const configured = config(["owner/repo"]); configured.issueEnrichment.maxIssuesPerBurst = 2; configured.issueEnrichment.repos["owner/repo"].maxIssuesPerBurst = 2; let evidenceReads = 0; prepareBranchWorktree.mockResolvedValue({ path: "/tmp/repo", headSha: "a".repeat(40) }); const result = await runIssueEnrichmentCycle({ config: configured, state: state(), github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [issue(1), issue(2)], listIssueCommentsForEnrichment: async () => { if (evidenceReads++ === 0) throw new Error("fixture evidence failure"); return Object.assign([], { items: [], rawCount: 0, truncated: false, overflow: false }); }, getIssueOrPull: async (_repo, number) => issue(number), canPostAsApp: () => true, upsertIssueComment: async ({ issueNumber }) => ({ action: "created" as const, id: issueNumber }) }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(result.summary).toMatchObject({ posted: 1, failed: 1 }); expect(prepareBranchWorktree).toHaveBeenCalledTimes(1); expect(result.items.find(({ issueNumber }) => issueNumber === 2)?.recordStatus).toBe("posted"); });
  it("refreshes expired deadlines and preserves active deferral reasons", async () => { const configured = config(["owner/repo"]), deferred = { repo: "owner/repo", issueNumber: 2, status: "deferred", issueUpdatedAt: "2026-08-26T09:00:00.000Z", nextEligibleAt: "2026-08-26T09:59:00.000Z" }; prepareBranchWorktree.mockResolvedValue({ path: "/tmp/repo", headSha: "a".repeat(40) }); const result = await runIssueEnrichmentCycle({ config: configured, state: persistentState([deferred]), github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [issue(1), issue(2)], getIssueOrPull: async (_repo, number) => issue(number), canPostAsApp: () => true, upsertIssueComment: async ({ issueNumber }) => ({ action: "created" as const, id: issueNumber }) }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(Date.parse(result.items.find(({ issueNumber }) => issueNumber === 2)!.nextEligibleAt!)).toBeGreaterThan(Date.parse("2026-08-26T10:00:00.000Z")); const activeState = persistentState([{ ...deferred, issueNumber: 3, reason: "burst_threshold_exceeded", nextEligibleAt: "2026-08-26T10:30:00.000Z" }]); await runIssueEnrichmentCycle({ config: configured, state: activeState, github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [issue(3)], canPostAsApp: () => true, upsertIssueComment: async () => { throw new Error("must not post"); } }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(activeState.getIssueEnrichmentRecord("owner/repo", 3)?.reason).toBe("burst_threshold_exceeded"); });
  it("applies the atomic burst gate after changed posted identities settle", async () => { const configured = config(["owner/repo"]); Object.assign(configured.issueEnrichment, { maxIssuesPerCycle: 2, maxCommentsPerCycle: 2, globalMaxIssuesPerCycle: 2, globalMaxCommentsPerCycle: 2 }); Object.assign(configured.issueEnrichment.repos["owner/repo"], { maxIssuesPerCycle: 2, maxCommentsPerCycle: 2 }); const records = [1, 2].map((issueNumber) => ({ repo: "owner/repo", issueNumber, status: "posted", issueUpdatedAt: "2026-08-26T09:00:00.000Z", analysisInputHash: "0".repeat(64) })), posted: number[] = []; prepareBranchWorktree.mockResolvedValue({ path: "/tmp/repo", headSha: "a".repeat(40) }); const result = await runIssueEnrichmentCycle({ config: configured, state: persistentState(records), github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [issue(1), issue(2)], getIssueOrPull: async (_repo, number) => issue(number), canPostAsApp: () => true, upsertIssueComment: async ({ issueNumber }) => { posted.push(issueNumber); return { action: "created" as const, id: issueNumber }; } }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(result.summary).toMatchObject({ posted: 0, deferredRecorded: 2 }); expect(posted).toEqual([]); });
  it("persists an unbounded terminal before caps without starving a healthy sibling", async () => {
    const configured = config(["owner/repo"]), shared = persistentState(), posts: number[] = [], watermarks: unknown[] = []; let terminalReads = 0;
    configured.issueEnrichment.repos["owner/repo"].promotionMaintainers = [{ login: "maintainer", validFrom: "2026-01-01T00:00:00.000Z" }]; shared.recordIssueEnrichmentRepoWatermark = (value: unknown) => { watermarks.push(value); return value as never; };
    const receipt = (terminal: "short_page" | "event_history_unbounded") => Object.assign([], { items: [], pagesRead: 1, rawCount: 0, uniqueCount: 0, duplicateCount: 0, terminal, truncated: terminal === "event_history_unbounded", overflow: terminal === "event_history_unbounded" });
    const terminalIssue = issue(1), promotionTerminalIssue = { ...issue(2), labels: [{ name: "upstream-intake" }, { name: "active-continuation" }] }; let terminalUpdatedAt = terminalIssue.updated_at;
    prepareBranchWorktree.mockResolvedValue({ path: "/tmp/repo", headSha: "a".repeat(40) });
    const permission = vi.fn(async () => "admin" as const), github = {
      getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async (_repo: string, options: { minIssueResults?: number; qualifyForMinimum?: (issue: ReturnType<typeof issue>) => Promise<boolean> }) => { expect(options.minIssueResults).toBe(2); const rows = [{ ...terminalIssue, updated_at: terminalUpdatedAt }, promotionTerminalIssue, issue(3)]; expect(await Promise.all(rows.map((row) => options.qualifyForMinimum!(row)))).toEqual([false, false, true]); return Object.assign(rows, { scanCompletion: "complete" as const }); },
      listIssueLabelEvents: async (_repo: string, number: number) => { if (number !== 3) terminalReads += 1; return receipt(number !== 3 ? "event_history_unbounded" : "short_page"); },
      getCollaboratorPermission: permission, getIssueOrPull: async (_repo: string, number: number) => issue(number), canPostAsApp: () => true,
      upsertIssueComment: async ({ issueNumber }: { issueNumber: number }) => { posts.push(issueNumber); return { action: "created" as const, id: issueNumber }; }
    };
    const first = await runIssueEnrichmentCycle({ config: configured, state: shared, github, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission });
    expect(first.summary).toMatchObject({ skipped: 2, skippedRecorded: 2, posted: 1 }); expect(first.items.find(({ issueNumber }) => issueNumber === 1)).toMatchObject({ action: "skipped", reason: "event_history_unbounded", recordStatus: "skipped" });
    expect(first.items.find(({ issueNumber }) => issueNumber === 2)).toMatchObject({ action: "skipped", reason: "event_history_unbounded", recordStatus: "skipped" }); expect(first.items.find(({ issueNumber }) => issueNumber === 3)?.recordStatus).toBe("posted");
    expect(posts).toEqual([3]); expect(runIssueAnalysis).toHaveBeenCalledTimes(1); expect(permission).not.toHaveBeenCalled(); expect(terminalReads).toBe(2); expect(watermarks).toHaveLength(1);
    const replay = await runIssueEnrichmentCycle({ config: configured, state: shared, github, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:01:00.000Z", licenseAdmission: admission });
    expect(replay.items.find(({ issueNumber }) => issueNumber === 1)).toMatchObject({ action: "skipped", reason: "event_history_unbounded", recordStatus: "skipped" }); expect(terminalReads).toBe(2);
    terminalUpdatedAt = "2026-08-26T09:30:00.000Z"; await runIssueEnrichmentCycle({ config: configured, state: shared, github, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:02:00.000Z", licenseAdmission: admission }); expect(terminalReads).toBe(3);
    await runIssueEnrichmentCycle({ config: configured, state: shared, github, dryRun: false, includeExisting: true, force: true, checkedAt: "2026-08-26T10:03:00.000Z", licenseAdmission: admission }); expect(terminalReads).toBe(5);
  });
  it("qualifies before event reads and isolates transport failure without overwriting settled state", async () => { const posted: number[] = [], eventReads: number[] = [], shared = persistentState([{ repo: "owner/repo", issueNumber: 4, status: "posted", issueUpdatedAt: "2026-08-26T09:00:00.000Z", analysisInputHash: "0".repeat(64) }]); prepareBranchWorktree.mockResolvedValue({ path: "/tmp/repo", headSha: "a".repeat(40) }); const result = await runIssueEnrichmentCycle({ config: config(["owner/repo"]), state: shared, github: { getRepo: async () => ({ default_branch: "main" }), listIssuesForEnrichment: async () => [{ ...issue(1), labels: [{ name: "upstream-intake" }, { name: "active-continuation" }] }, issue(2), issue(4), issue(3)], listIssueLabelEvents: async (_repo, number) => { eventReads.push(number); if (number === 2 || number === 4) throw new Error("fixture event transport failure"); return Object.assign([], { items: [], rawCount: 0, truncated: false, overflow: false }); }, getIssueOrPull: async (_repo, number) => issue(number), canPostAsApp: () => true, upsertIssueComment: async ({ issueNumber }) => { posted.push(issueNumber); return { action: "created" as const, id: issueNumber }; } }, dryRun: false, includeExisting: true, checkedAt: "2026-08-26T10:00:00.000Z", licenseAdmission: admission }); expect(eventReads).toEqual([2, 4, 3]); expect(result.items.find(({ issueNumber }) => issueNumber === 1)).toMatchObject({ action: "skipped", reason: "preservation_only_upstream_intake" }); expect(result.items.find(({ issueNumber }) => issueNumber === 2)?.recordStatus).toBe("failed"); expect(result.items.find(({ issueNumber }) => issueNumber === 4)).toBeUndefined(); expect(shared.getIssueEnrichmentRecord("owner/repo", 4)?.status).toBe("posted"); expect(result.items.find(({ issueNumber }) => issueNumber === 3)?.recordStatus).toBe("posted"); expect(result.summary).toMatchObject({ failed: 1, posted: 1 }); expect(posted).toEqual([3]); });
});
