// Generated by scripts/generate-secret-rules.mjs from shared/canonical-secret-rules.json. DO NOT EDIT.
import Foundation

extension CanonicalSecretRule {
    static let generated: [CanonicalSecretRule] = [
        CanonicalSecretRule(id: "github-prefixed-token", source: "\\bgh[pousr]_[A-Za-z0-9_]{8,}\\b", ignoreCase: false),
        CanonicalSecretRule(id: "github-fine-grained-token", source: "\\bgithub_pat_[A-Za-z0-9_]{8,}\\b", ignoreCase: false),
        CanonicalSecretRule(id: "sk-provider-key", source: "\\bsk-[A-Za-z0-9_-]{8,}\\b", ignoreCase: false),
        CanonicalSecretRule(id: "bearer-credential", source: "\\bBearer\\s+[A-Za-z0-9._~+/=-]{20,}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "credential-url", source: "https?://[^/\\s@]+@[^/\\s]+", ignoreCase: true),
        CanonicalSecretRule(id: "aws-access-key", source: "\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b", ignoreCase: false),
        CanonicalSecretRule(id: "slack-token", source: "\\bxox[baprs]-[A-Za-z0-9-]{10,}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "query-credential", source: "[?&](?:access[_-]?token|auth[_-]?token|api[_-]?key|token|secret|session|cookie)=[A-Za-z0-9._~+/=-]{16,}", ignoreCase: true),
        CanonicalSecretRule(id: "customer-id", source: "\\bcustomer[_-]?id\\b\\s*[:=]\\s*[\"']?cus_[A-Za-z0-9]{8,}", ignoreCase: true),
        CanonicalSecretRule(id: "customer-ssn", source: "\\b(?:customer|client)[_-]?ssn\\b\\s*[:=]\\s*[\"']?\\d{3}-\\d{2}-\\d{4}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "customer-phone", source: "\\b(?:customer|client)[_-]?phone\\b\\s*[:=]\\s*[\"']?\\+?\\d[\\d ().-]{7,}\\d\\b", ignoreCase: true),
        CanonicalSecretRule(id: "named-credential", source: "\\b(?:api[_-]?key|token|secret|password|cookie|session)\\b\\s*[:=]\\s*[\"']?[A-Za-z0-9._~+/=-]{16,}", ignoreCase: true),
        CanonicalSecretRule(id: "neondiff-underscore-license", source: "\\b(?:NEONDIFF|NDL|LIC)_[A-Za-z0-9][A-Za-z0-9_-]{11,}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "neondiff-live-license", source: "\\bnd_live_[A-Za-z0-9_-]{8,}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "neondiff-hyphen-license", source: "(?<![A-Za-z0-9_./-])(?:[Nn][Ee][Oo][Nn][Dd][Ii][Ff][Ff]|[Nn][Dd][Ll]|[Ll][Ii][Cc])-(?=[A-Za-z0-9_-]*[A-Z0-9])[A-Za-z0-9][A-Za-z0-9_-]{11,}\\b", ignoreCase: false),
        CanonicalSecretRule(id: "hyphenated-named-credential", source: "\\b[A-Za-z0-9]{3,}[-_](?:secret|token|password|cookie)[-_][A-Za-z0-9_-]{3,}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "email-address", source: "\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b", ignoreCase: true),
        CanonicalSecretRule(id: "complete-private-key", source: "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*PRIVATE KEY-----", ignoreCase: false),
        CanonicalSecretRule(id: "truncated-private-key", source: "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]*", ignoreCase: false),
    ]
}

extension CanonicalSensitiveCookieRule {
    static let generated = CanonicalSensitiveCookieRule(id: "sensitive-cookie-header", prefix: "cookie:", sensitiveNameSource: "(?:session|token|auth|secret|cookie)", maximumAttributes: 1000)
}

enum CanonicalSecretSafeLiterals {
    static let generated = ["NEONDIFF_GITHUB_APP_ID", "NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH", "NEONDIFF_PROTECTED_CHECKOUT_ROOT", "NEONDIFF_LICENSE_KEY", "NEONDIFF_PROVIDER_API_KEY", "NEONDIFF_ALLOW_REMOTE_SMOKE", "missing_secret_env", "neondiff-openwiki-context-ab-v0.1", "neondiff-openwiki-docs-drift-v0.1"]
}

#if DEBUG
@_spi(Testing) public enum CanonicalSecretRuleCorpus {
    public static let ruleIDs = ["github-prefixed-token", "github-fine-grained-token", "sk-provider-key", "bearer-credential", "credential-url", "aws-access-key", "slack-token", "query-credential", "customer-id", "customer-ssn", "customer-phone", "named-credential", "neondiff-underscore-license", "neondiff-live-license", "neondiff-hyphen-license", "hyphenated-named-credential", "email-address", "complete-private-key", "truncated-private-key", "sensitive-cookie-header"]
    public static let sensitive: [(id: String, text: String)] = [
        ("github-prefixed-token", "ghp_abcdefgh"),
        ("github-fine-grained-token", "github_pat_abcdefgh"),
        ("sk-provider-key", "sk-abcdefgh"),
        ("bearer-credential", "Bearer abcdefghijklmnopqrst"),
        ("credential-url", "https://user:p4ss@example.com/path"),
        ("aws-access-key", "AKIA1234567890ABCDEF"),
        ("slack-token", "xoxb-abcdefghij"),
        ("query-credential", "?access_token=abcdefghijklmnop"),
        ("customer-id", "customer_id=cus_abcdefgh"),
        ("customer-ssn", "client_ssn=123-45-6789"),
        ("customer-phone", "customer_phone=+1 (415) 555-0123"),
        ("named-credential", "password=abcdefghijklmnop"),
        ("neondiff-underscore-license", "NEONDIFF_abcdefghijkl"),
        ("neondiff-live-license", "nd_live_abcdefgh"),
        ("neondiff-hyphen-license", "NDL-XQKM-RPYB-SUTE"),
        ("hyphenated-named-credential", "super-secret-token"),
        ("email-address", "person@example.com"),
        ("complete-private-key", ["-----BEGIN ", "PRIVATE KEY-----\\nabc\\n-----END ", "PRIVATE KEY-----"].joined()),
        ("truncated-private-key", ["-----BEGIN ", "PRIVATE KEY-----\\nabc"].joined()),
        ("sensitive-cookie-header", "Cookie: theme=light; session=x"),
    ]
    public static let benign: [(id: String, text: String)] = [
        ("ordinary-provider-status", "Provider metadata endpoint is healthy."),
        ("short-sk-fragment", "sk-short"),
        ("ordinary-neondiff-path", "/tmp/neondiff-launchd-plist-Ov4D5v/com.example.neondiff.plist"),
        ("lowercase-license-label", "lic-diagnostic-reference-without-key-material"),
        ("safe-environment-names", "Set NEONDIFF_GITHUB_APP_ID, NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH, NEONDIFF_LICENSE_KEY, and NEONDIFF_PROVIDER_API_KEY."),
        ("non-sensitive-cookie", "Cookie: theme=light; locale=en-US"),
        ("customer-label", "customer_id = acme-corporation-12345"),
    ]
}
#endif
