// Generated by scripts/generate-secret-rules.mjs from shared/canonical-secret-rules.json. DO NOT EDIT.
export interface CanonicalSecretRule { readonly id: string; readonly source: string; readonly ignoreCase: boolean; }
export interface CanonicalSecretFixture { readonly id: string; readonly text: string; }
export const canonicalSecretRules: readonly CanonicalSecretRule[] = [
  {
    "id": "github-prefixed-token",
    "source": "\\bgh[pousr]_[A-Za-z0-9_]{8,}\\b",
    "ignoreCase": false
  },
  {
    "id": "github-fine-grained-token",
    "source": "\\bgithub_pat_[A-Za-z0-9_]{8,}\\b",
    "ignoreCase": false
  },
  {
    "id": "sk-provider-key",
    "source": "\\bsk-[A-Za-z0-9_-]{8,}\\b",
    "ignoreCase": false
  },
  {
    "id": "bearer-credential",
    "source": "\\bBearer\\s+[A-Za-z0-9._~+/=-]{20,}\\b",
    "ignoreCase": true
  },
  {
    "id": "credential-url",
    "source": "https?:\\/\\/[^/\\s@]+@[^/\\s]+",
    "ignoreCase": true
  },
  {
    "id": "aws-access-key",
    "source": "\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b",
    "ignoreCase": false
  },
  {
    "id": "slack-token",
    "source": "\\bxox[baprs]-[A-Za-z0-9-]{10,}\\b",
    "ignoreCase": true
  },
  {
    "id": "query-credential",
    "source": "[?&](?:access[_-]?token|auth[_-]?token|api[_-]?key|token|secret|session|cookie)=[A-Za-z0-9._~+/=-]{16,}",
    "ignoreCase": true
  },
  {
    "id": "customer-id",
    "source": "\\bcustomer[_-]?id\\b\\s*[:=]\\s*[\"']?cus_[A-Za-z0-9]{8,}",
    "ignoreCase": true
  },
  {
    "id": "customer-ssn",
    "source": "\\b(?:customer|client)[_-]?ssn\\b\\s*[:=]\\s*[\"']?\\d{3}-\\d{2}-\\d{4}\\b",
    "ignoreCase": true
  },
  {
    "id": "customer-phone",
    "source": "\\b(?:customer|client)[_-]?phone\\b\\s*[:=]\\s*[\"']?\\+?\\d[\\d ().-]{7,}\\d\\b",
    "ignoreCase": true
  },
  {
    "id": "named-credential",
    "source": "\\b(?:api[_-]?key|token|secret|password|cookie|session)\\b\\s*[:=]\\s*[\"']?[A-Za-z0-9._~+/=-]{16,}",
    "ignoreCase": true
  },
  {
    "id": "neondiff-underscore-license",
    "source": "\\b(?:NEONDIFF|NDL|LIC)_[A-Za-z0-9][A-Za-z0-9_-]{11,}\\b",
    "ignoreCase": true
  },
  {
    "id": "neondiff-live-license",
    "source": "\\bnd_live_[A-Za-z0-9_-]{8,}\\b",
    "ignoreCase": true
  },
  {
    "id": "neondiff-hyphen-license",
    "source": "(?<![A-Za-z0-9_./-])(?:[Nn][Ee][Oo][Nn][Dd][Ii][Ff][Ff]|[Nn][Dd][Ll]|[Ll][Ii][Cc])-(?=[A-Za-z0-9_-]*[A-Z0-9])[A-Za-z0-9][A-Za-z0-9_-]{11,}\\b",
    "ignoreCase": false
  },
  {
    "id": "hyphenated-named-credential",
    "source": "\\b[A-Za-z0-9]{3,}[-_](?:secret|token|password|cookie)[-_][A-Za-z0-9_-]{3,}\\b",
    "ignoreCase": true
  },
  {
    "id": "email-address",
    "source": "\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b",
    "ignoreCase": true
  },
  {
    "id": "complete-private-key",
    "source": "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*PRIVATE KEY-----",
    "ignoreCase": false
  },
  {
    "id": "truncated-private-key",
    "source": "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]*",
    "ignoreCase": false
  }
];
export const canonicalSensitiveCookieRule = {
  "id": "sensitive-cookie-header",
  "prefix": "cookie:",
  "sensitiveNameSource": "(?:session|token|auth|secret|cookie)",
  "maximumAttributes": 1000,
  "sample": "Cookie: theme=light; session=x"
} as const;
export const canonicalSecretSafeLiterals: readonly string[] = [
  "NEONDIFF_GITHUB_APP_ID",
  "NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH",
  "NEONDIFF_PROTECTED_CHECKOUT_ROOT",
  "NEONDIFF_LICENSE_KEY",
  "NEONDIFF_PROVIDER_API_KEY",
  "NEONDIFF_ALLOW_REMOTE_SMOKE",
  "missing_secret_env",
  "neondiff-openwiki-context-ab-v0.1",
  "neondiff-openwiki-docs-drift-v0.1"
];
export const canonicalSecretRuleCorpus = {
  ruleIds: [
  "github-prefixed-token",
  "github-fine-grained-token",
  "sk-provider-key",
  "bearer-credential",
  "credential-url",
  "aws-access-key",
  "slack-token",
  "query-credential",
  "customer-id",
  "customer-ssn",
  "customer-phone",
  "named-credential",
  "neondiff-underscore-license",
  "neondiff-live-license",
  "neondiff-hyphen-license",
  "hyphenated-named-credential",
  "email-address",
  "complete-private-key",
  "truncated-private-key",
  "sensitive-cookie-header"
],
  sensitive: [
    { id: "github-prefixed-token", text: "ghp_abcdefgh" },
    { id: "github-fine-grained-token", text: "github_pat_abcdefgh" },
    { id: "sk-provider-key", text: "sk-abcdefgh" },
    { id: "bearer-credential", text: "Bearer abcdefghijklmnopqrst" },
    { id: "credential-url", text: "https://user:p4ss@example.com/path" },
    { id: "aws-access-key", text: "AKIA1234567890ABCDEF" },
    { id: "slack-token", text: "xoxb-abcdefghij" },
    { id: "query-credential", text: "?access_token=abcdefghijklmnop" },
    { id: "customer-id", text: "customer_id=cus_abcdefgh" },
    { id: "customer-ssn", text: "client_ssn=123-45-6789" },
    { id: "customer-phone", text: "customer_phone=+1 (415) 555-0123" },
    { id: "named-credential", text: "password=abcdefghijklmnop" },
    { id: "neondiff-underscore-license", text: "NEONDIFF_abcdefghijkl" },
    { id: "neondiff-live-license", text: "nd_live_abcdefgh" },
    { id: "neondiff-hyphen-license", text: "NDL-XQKM-RPYB-SUTE" },
    { id: "hyphenated-named-credential", text: "super-secret-token" },
    { id: "email-address", text: "person@example.com" },
    { id: "complete-private-key", text: ["-----BEGIN ", "PRIVATE KEY-----\\nabc\\n-----END ", "PRIVATE KEY-----"].join("") },
    { id: "truncated-private-key", text: ["-----BEGIN ", "PRIVATE KEY-----\\nabc"].join("") },
    { id: "sensitive-cookie-header", text: "Cookie: theme=light; session=x" },
  ],
  benign: [
  {
    "id": "ordinary-provider-status",
    "text": "Provider metadata endpoint is healthy."
  },
  {
    "id": "short-sk-fragment",
    "text": "sk-short"
  },
  {
    "id": "ordinary-neondiff-path",
    "text": "/tmp/neondiff-launchd-plist-Ov4D5v/com.example.neondiff.plist"
  },
  {
    "id": "lowercase-license-label",
    "text": "lic-diagnostic-reference-without-key-material"
  },
  {
    "id": "safe-environment-names",
    "text": "Set NEONDIFF_GITHUB_APP_ID, NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH, NEONDIFF_LICENSE_KEY, and NEONDIFF_PROVIDER_API_KEY."
  },
  {
    "id": "non-sensitive-cookie",
    "text": "Cookie: theme=light; locale=en-US"
  },
  {
    "id": "customer-label",
    "text": "customer_id = acme-corporation-12345"
  }
]
} as const;
