// Generated by scripts/generate-secret-rules.mjs from shared/canonical-secret-rules.json. DO NOT EDIT.
export interface CanonicalSecretRule { readonly id: string; readonly source: string; readonly ignoreCase: boolean; }
export const canonicalSecretRules: readonly CanonicalSecretRule[] = [
  {
    "id": "github-prefixed-token",
    "source": "\\bgh[pousr]_[A-Za-z0-9_]{8,}\\b",
    "ignoreCase": false
  },
  {
    "id": "github-fine-grained-token",
    "source": "\\bgithub_pat_[A-Za-z0-9_]{8,}\\b",
    "ignoreCase": false
  },
  {
    "id": "sk-provider-key",
    "source": "\\bsk-[A-Za-z0-9_-]{8,}\\b",
    "ignoreCase": false
  },
  {
    "id": "bearer-credential",
    "source": "\\bBearer\\s+[A-Za-z0-9._~+/=-]{20,}\\b",
    "ignoreCase": true
  },
  {
    "id": "credential-url",
    "source": "https?:\\/\\/[^/\\s@]+@[^/\\s]+",
    "ignoreCase": true
  },
  {
    "id": "aws-access-key",
    "source": "\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b",
    "ignoreCase": false
  },
  {
    "id": "slack-token",
    "source": "\\bxox[baprs]-[A-Za-z0-9-]{10,}\\b",
    "ignoreCase": true
  },
  {
    "id": "query-credential",
    "source": "[?&](?:access[_-]?token|auth[_-]?token|api[_-]?key|token|secret|session|cookie)=[A-Za-z0-9._~+/=-]{16,}",
    "ignoreCase": true
  },
  {
    "id": "customer-id",
    "source": "\\bcustomer[_-]?id\\b\\s*[:=]\\s*[\"']?cus_[A-Za-z0-9]{8,}",
    "ignoreCase": true
  },
  {
    "id": "customer-ssn",
    "source": "\\b(?:customer|client)[_-]?ssn\\b\\s*[:=]\\s*[\"']?\\d{3}-\\d{2}-\\d{4}\\b",
    "ignoreCase": true
  },
  {
    "id": "customer-phone",
    "source": "\\b(?:customer|client)[_-]?phone\\b\\s*[:=]\\s*[\"']?\\+?\\d[\\d ().-]{7,}\\d\\b",
    "ignoreCase": true
  },
  {
    "id": "named-credential",
    "source": "\\b(?:api[_-]?key|token|secret|password|cookie|session)\\b\\s*[:=]\\s*[\"']?[A-Za-z0-9._~+/=-]{16,}",
    "ignoreCase": true
  },
  {
    "id": "neondiff-underscore-license",
    "source": "\\b(?:NEONDIFF|NDL|LIC)_[A-Za-z0-9][A-Za-z0-9_-]{11,}\\b",
    "ignoreCase": true
  },
  {
    "id": "neondiff-live-license",
    "source": "\\bnd_live_[A-Za-z0-9_-]{8,}\\b",
    "ignoreCase": true
  },
  {
    "id": "neondiff-hyphen-license",
    "source": "(?<![A-Za-z0-9_./-])(?:[Nn][Ee][Oo][Nn][Dd][Ii][Ff][Ff]|[Nn][Dd][Ll]|[Ll][Ii][Cc])-(?=[A-Za-z0-9_-]*[A-Z0-9])[A-Za-z0-9][A-Za-z0-9_-]{11,}\\b",
    "ignoreCase": false
  },
  {
    "id": "hyphenated-named-credential",
    "source": "\\b[A-Za-z0-9]{3,}[-_](?:secret|token|password|cookie)[-_][A-Za-z0-9_-]{3,}\\b",
    "ignoreCase": true
  },
  {
    "id": "email-address",
    "source": "\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b",
    "ignoreCase": true
  },
  {
    "id": "complete-private-key",
    "source": "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*PRIVATE KEY-----",
    "ignoreCase": false
  },
  {
    "id": "truncated-private-key",
    "source": "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]*",
    "ignoreCase": false
  }
];
export const canonicalSensitiveCookieRule = {
  "id": "sensitive-cookie-header",
  "prefix": "cookie:",
  "sensitiveNameSource": "(?:session|token|auth|secret|cookie)",
  "maximumAttributes": 1000,
  "sample": "Cookie: theme=light; session=x"
} as const;
export const canonicalSecretSafeLiterals: readonly string[] = [
  "NEONDIFF_GITHUB_APP_ID",
  "NEONDIFF_GITHUB_APP_PRIVATE_KEY_PATH",
  "NEONDIFF_PROTECTED_CHECKOUT_ROOT",
  "NEONDIFF_LICENSE_KEY",
  "NEONDIFF_PROVIDER_API_KEY",
  "NEONDIFF_ALLOW_REMOTE_SMOKE",
  "missing_secret_env",
  "neondiff-openwiki-context-ab-v0.1",
  "neondiff-openwiki-docs-drift-v0.1"
];
